[platformio]
default_envs = native

[env:native]
platform = native
build_flags =
  -D HOST_BUILD

test_filter = test_host

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D BLINK_INTERVAL_MS=500

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_flags =
  -D BLINK_INTERVAL_MS=500
